### ISSUE TITLE
Support IKEv2

### ISSUE THREAD

**Issue by calexandru2018** [calexandru2018/linux-gui-legacy#32]
Automate IKEv2 connection creation, based on protonvpn instructions: https://protonvpn.com/support/linux-ikev2-protonvpn/

**Comment by Zeioth** [comment]
Linked to [151](https://github.com/ProtonVPN/protonvpn-cli-ng/issues/151) 

I've been reading the [cli source](https://github.com/ProtonVPN/protonvpn-cli-ng/blob/master/protonvpn_cli/cli.py) code and it's super clear.

**Comment by calexandru2018** [comment]
This should be firstly implemented within the CLI.
