### ISSUE TITLE
GUI Size for smaller screens

### ISSUE THREAD

**Issue by anthonyh-uk** [calexandru2018/linux-gui-legacy#36]
I use a smaller laptop with 1368 x 768 and find the GUI will not fit reasonably on the page.

I’m not a programmer but I’m so impressed with this software that I’m hoping there’s a way to shrink it a bit smaller for us small screen users.

Perhaps reducing the font size in the upper section? I’m not sure what’s possible and accept there may be other priorities.

Either way keep up the good work.

**Comment by anthonyh-uk** [comment]
![image](https://user-images.githubusercontent.com/63021385/79041770-43e70a00-7bea-11ea-9f77-a4b287dc3921.png)


picture to illustrate .. Ubuntu Mate desktop

**Comment by calexandru2018** [comment]
Hi @anthonyh-uk, thank you for reporting the issue here. To be honest, when I was developing this GUI I have not thought about smaller resolutions, but now I see that it can cause problems. In the next version (v2), this should be addressed, since the GUI will be redesigned so it should perfectly accommodate smaller screens/resolutions. :)

**Comment by anthonyh-uk** [comment]
Thanks for prompt reply and I look forward to the redesign. All the best, Anthony H

**Comment by calexandru2018** [comment]
Here is a [sneak peak](https://imgur.com/MyiyfFR) of the v2 @anthonyh-uk  !

**Comment by anthonyh-uk** [comment]
Looks very smooth. Will it be more portrait than landscape?

**Comment by calexandru2018** [comment]
> Looks very smooth. Will it be more portrait than landscape?

Yes, so it should play really well on smaller screens, give it a try!

**Comment by anthonyh-uk** [comment]
Hi again, also a small matter which I explain in this picture and I think will also be of interest. The text should have said " open _the GUI via_ the tray".
![pvpn-tray-2020 04 17th](https://user-images.githubusercontent.com/63021385/79614359-453b9980-80f8-11ea-87ea-f4f963a2b1d1.png)

**Comment by calexandru2018** [comment]
Hi again @anthonyh-uk , which distro are you on ? I would like to replicate the issue. Or rather, create a new issue with a new screen-shot if this is still occurring. Sorry for the delayed response.

**Comment by anthonyh-uk** [comment]
Hi again, thanks for considering this, I thought afterwards maybe I posted it in the wrong place and should have made a new issue so I'm grateful for your reply.

I'm using stock Ubuntu-Mate-Release 19.10 (Eoan Ermine) 64-bit  with MATE 1.22.2 from https://ubuntu-mate.org/

I've not changed the default panels themselves, only added a lot of items and links to software.

Let me know if you can recreate this, if having trouble maybe I can help.

AnthonyH-UK

**Comment by calexandru2018** [comment]
@anthonyh-uk please do create a new issue for this, as it would be easier for me to handle it. Fill out the issue template much as you can (by answering to the questions/points) and also provide any screenshots if you have. Appreciated :)

**Comment by anthonyh-uk** [comment]
Hi again and sorry not to raised a new issue before now, I found that I could not recreate the event after a few tries and think it may as well have been a one off. So thanks but consider it no further.
Looking forward to the new release sometime. If you'd like me to give it run at some point for feedback do send me a message saying how. All the best, AnthonyH-UK
