### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by Libriste** [calexandru2018/linux-gui-legacy#51]
Since we're not able to leave a simple comment on GitHub, I'll use the issues section, sorry.

Thank you for this app, seems like ProtonVPN team is too fckn lazy to develop a little GUI for Linux, but when it's about Windows and Mac they have plenty of time !

You did the work they should have done, thank you.

**Comment by calexandru2018** [comment]
Thank you @Libriste hope you enjoy it!
