### ISSUE TITLE
UX: add user-feedback (notification) when connecting/disconnecting

### ISSUE THREAD

**Issue by Heziode** [calexandru2018/linux-gui-legacy#54]
Currently, the app does not provide a user feedback when we are connecting to a server (like PIA for example), so we cannot know (until successfully connecting) if our action has been taken into account.

What I propose:

- Add a notification when we are connecting to a server (and precise in the connection, which server)
- Add a notification when the connection is (un-)successfully

**Comment by calexandru2018** [comment]
Hi @Heziode :)

I am not sure if I understand, because whenever you connect or disconnect from within the GUI, a "status" message is always displayed, be it during connecting or disconnecting. Are you perhaps referring to when you're connecting/disconnecting via the tray icon ?

**Comment by Heziode** [comment]
> Are you perhaps referring to when you're connecting/disconnecting via the tray icon ?

Yes.

For example, if I click on the quick connect on the main menu, the menu just close, so I don't know if I miss click, if my action has been taken into account, or what else. A notification can tell me.

**Comment by calexandru2018** [comment]
@Heziode I agree to the fact that there is some room for improvement in that regard. I'll look into it and see what can be done, until then you'll have to rely on the green/orange icons. 
Marking this as enhancement :+1:

**Comment by calexandru2018** [comment]
This has been implemented with #67
