### ISSUE TITLE
ModuleNotFoundError: No module named 'gi'

### ISSUE THREAD

**Issue by d8sconz** [calexandru2018/linux-gui-legacy#68]
All dependencies are installed, latest versions:

sudo apt install -y python3-gi python3-gi-cairo gir1.2-gtk-3.0Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-gi is already the newest version (3.20.0-0ubuntu1).
python3-gi-cairo is already the newest version (3.20.0-0ubuntu1).
gir1.2-gtk-3.0 is already the newest version (3.18.9-1ubuntu3.3).
0 upgraded, 0 newly installed, 0 to remove and 90 not upgraded.

When launching however:
# sudo protonvpn-gui
Traceback (most recent call last):
  File "/usr/local/bin/protonvpn-gui", line 6, in <module>
    from protonvpn_linux_gui.gui import initialize_gui
  File "/usr/local/lib/python3.8/site-packages/protonvpn_linux_gui/gui.py", line 16, in <module>
    from .utils import (
  File "/usr/local/lib/python3.8/site-packages/protonvpn_linux_gui/utils.py", line 46, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'

 - Linux Mint 18.3 Sylvia
 - Firefox 75.0

**Comment by calexandru2018** [comment]
Hi @d8sconz :)

Thank you for reporting. I would like to ask you to please updated your issue in accordance to the template so that I can get as much info as possible in order to help. Much appreciated :+1:

**Comment by d8sconz** [comment]
Couldn't see anything I missed from the template. What do you need to know?

**Comment by calexandru2018** [comment]
@d8sconz some additional screenshots or a description if run from within a virtual environment or not.

**Comment by d8sconz** [comment]
Not run from a venv. Nothing happens so nothing to screenshoot. Have pasted
terminal output in OP.

**Comment by d8sconz** [comment]
I have to go out now but I'll check my $PATH when I get back to see if that
can help.

**Comment by calexandru2018** [comment]
Hi @d8sconz could you please update the status ?

**Comment by d8sconz** [comment]
Hi Alexandru. You can mark it as closed if you wish, but I only resolved it
by removing it from my system. The protonvpn program wasn't working either.
I could never get it to connect. Then it conflicted with my existing vpn
setup so I just took it all off. Sorry, I should have updated. It's a great
program but I just don't have the time to get it working for now.

**Comment by calexandru2018** [comment]
@d8sconz alright. I will be closing this issue. Later on, if you experience the same issue again, just create another issue or email me.
