### ISSUE TITLE
Split tunneling for apps

### ISSUE THREAD

**Issue by cubecraftgalaxy** [calexandru2018/linux-gui-legacy#73]
There doesn't appear to be a way to exclude apps as only ips can be excluded. This makes it much harder to for instance have a separate browser that isn't using the vpn

**Comment by calexandru2018** [comment]
Hi @cubecraftgalaxy  :)

Please search for previous issues before creating a new one, as this has already been asked by a previous user, and an explanation was given #53 

I will close this issue shortly after. :+1:
