### ISSUE TITLE
How to uninstall with setup.py

### ISSUE THREAD

**Issue by danielpza** [calexandru2018/linux-gui-legacy#76]
I installed linux-gui from github following the instruction in the readme a while ago using the command `setup.py install`. Now I want to reinstall it from the aur package https://aur.archlinux.org/packages/protonvpn-linux-gui/ but it doesn't allow me to install because it exist already (from my previous manual install).

So is there a way to uninstall it with setup.py or other methods?, I tried searching with `setup.py --help-commands` but couldn't find any commands.

**Comment by calexandru2018** [comment]
Hello @danielpza  :)

To uninstall the GUI you do the same thing as with the CLI or any python package, `sudo pip3 uninstall protonvpn-gui`. 
Either way I will add it to the readme so it is more clear :+1:

**Comment by danielpza** [comment]
Yep, that worked. I don't use python much so couldn't figure out it used pip when installing :smile:.

Good job with the project, Cheers.

**Comment by calexandru2018** [comment]
No worries @danielpza , we're here to help :D
