### ISSUE TITLE
cannot import name 'make_ovpn_template' with CLI >=2.2.3

### ISSUE THREAD

**Issue by calexandru2018** [calexandru2018/linux-gui-legacy#83]
The GUI does not start with the latest version of the CLI.

The issue is due to that GUI does not support CLI >= v.2.2.3, since the CLI has deprecated the function `make_ovpn_template`. <b>This is already fixed in the master branch</b>, although not pushed to  PyPi,  due to some other updates that the GUI will suffer.

<b>Temporary solution: </b>
- Downgrade CLI to v2.2.2
`sudo pip3 install protonvpn-cli==2.2.2 --upgrade` <br>
<b>or</b>
- Clone master branch

This has already been mentioned in #72, #75, #79 and #83

**Comment by SCCOBN** [comment]
2.2.4 of cli is out already, I'm still stuck with 2.2.2 due to linux_gui issue. When can I upgrade already?

**Comment by calexandru2018** [comment]
> 2.2.4 of cli is out already, I'm still stuck with 2.2.2 due to linux_gui issue. When can I upgrade already? 

This is going to be addressed in the coming weeks, stay tuned.

You can always clone from the master branch since that version is fully compatible, although installing from arch repo or PIP won't work unless you downgrade the CLI version.

**Comment by calexandru2018** [comment]
This issue should now be fixed, with v2.1.0 being released on PyPi and Arch.
