### ISSUE TITLE
protonvpn-gui refuses to start complaining '-gtk-icon-effect' is not a valid property name

### ISSUE THREAD

**Issue by mdoube** [calexandru2018/linux-gui-legacy#99]
**Describe the bug**
protonvpn-gui refuses to start and complains:
```
user@machine:~$ sudo protonvpn-gui
Traceback (most recent call last):
  File "/usr/local/bin/protonvpn-gui", line 11, in <module>
    sys.exit(init())
  File "/usr/local/lib/python3.5/dist-packages/linux_gui/protonvpn_gui.py", line 66, in init
    style_provider.load_from_path(UI_STYLES)
GLib.Error: gtk-css-provider-error-quark: common.css:51:20'-gtk-icon-effect' is not a valid property name (3)
```

**To Reproduce**
1. Install protonvpn-gui according to the instructions
2. Run protonvpn-gui at the command line

**Expected behavior**
protonvpn-gui runs and displays the GUI

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04 LTS (up to date)
 - Python: 3.5.2 (but `python -V` returns `2.7.12`)

**Comment by calexandru2018** [comment]
Hello @mdoube  :)

Thank you for posting this issue, although this has been already answered at #85. Ubuntu 16.04 is not supported due to the (old) version of GTK. The only way for it to work for you is by updating to Ubuntu 18.04.

Please close this issue if you manage to fix this 👍🏻

**Comment by mdoube** [comment]
> this has been already answered at #85

Thanks @calexandru2018 for noting the duplicate.

Perhaps it is worth considering what new features of GTK 3.22 (Ubuntu 18.04) compared to GTK 3.20 (Ubuntu 16.04) are so essential as to make it impossible to run the software? If it is just a minor cosmetic icon shading effect or similar (as the error message hints), you'd have to ask whether cutting off those users is worth it. I have no plans to update this machine or the others I have in the absence of a much more compelling reason, but I have really no idea how many other users are in the same position.
If there is really no will to maximise compatibility then this issue should be closed as a duplicate of #85 .

**Comment by calexandru2018** [comment]
I understand your situation, but I've previously tried to to remove any lines that were complaining about `-gtk-icon-effect` and it started to give me errors with the import tool, which indicated that versions below GTK3.22 had changed on how the internals worked. Also, Ubuntu 16.04 is approaching EOL, therefore as of at the moment, I don't think that support for ubuntu 16.04 will be incorporated. Nonetheless you could use the CLI, since it does not require any graphical dependencies.

**Comment by mdoube** [comment]
OK, thanks for the details. The tray icon is working well enough so will be limited to that plus cli for now.

Closing as duplicate of #85
